# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 8.10.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定网站源码分支，因人而异。hexo网站源码托管在独立repo则不用设置此项
branches:
  only:
    - master 

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - cd src
  - hexo clean
  - hexo generate
  - git config user.name "Roby"
  - git config user.email "robortly@163.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
# End: Build LifeCycle