# reference:
#   1. https://github.com/docker/build-push-action/blob/master/docs/advanced/push-multi-registries.md
#   2. https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md

name: Deploy to Production environment
on:
  push:
    tags:
      - v*
env:
  ARTIFACT_PATH: artifact.tar
  BOX_NAME: kys-ows
  BOX_URL: kaiyuanshe/kys-ows

jobs:
  deploy_docker_image:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - run: git submodule update --remote

      - name: Inject Environment variables
        run: |
          cat >> .npmrc <<EOF
          //npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}
          @kaiyuanshe:registry=https://npm.pkg.github.com
          always-auth=true
          EOF
          cat > .env.local <<EOF
          ${{ secrets.ENV_FILE }}
          VERCEL_URL=kaiyuanshe.cn
          EOF
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          tags: ${{ env.BOX_URL }}:latest
          outputs: type=docker,dest=${{ env.ARTIFACT_PATH }}

      - name: Pick Docker Compose
        run: |
          mkdir ./build
          mv ${{ env.ARTIFACT_PATH }} ./docker-compose.yml ./start.sh ./build

      - name: Transport Image
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./build
          remote: /tmp/${{ env.BOX_NAME }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_KEY }}

      - name: Run Image
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_KEY }}
          command: |
            cd /tmp/${{ env.BOX_NAME }}
            mkdir -p ~/${{ env.BOX_NAME }}
            mv docker-compose.yml start.sh ~/${{ env.BOX_NAME }}
            cd ~/${{ env.BOX_NAME }}
            chmod +x start.sh
            echo '${{ secrets.SSH_KEY }}' | sudo -S ./start.sh /tmp/${{ env.BOX_NAME }}/${{ env.ARTIFACT_PATH }}
