name: CI & CD
on:
  push:
    branches:
      - main
jobs:
  Build-and-Deploy:
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ env.VERCEL_TOKEN && env.VERCEL_ORG_ID && env.VERCEL_PROJECT_ID }}
        with:
          submodules: recursive
          lfs: true
      - run: git submodule update --remote

      - name: Deploy to Vercel
        id: vercel-deployment
        uses: amondnet/vercel-action@v25
        if: ${{ env.VERCEL_TOKEN && env.VERCEL_ORG_ID && env.VERCEL_PROJECT_ID }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: --prod

      - name: Lark notification
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.LARK_CHATBOT_HOOK_URL }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: Vercel 预览环境
                content:
                  - - tag: text
                      text: Git 仓库：
                    - tag: a
                      text: ${{ github.server_url }}/${{ github.repository }}
                      href: ${{ github.server_url }}/${{ github.repository }}
                  - - tag: text
                      text: 代码分支：
                    - tag: a
                      text: ${{ github.ref }}
                      href: ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}
                  - - tag: text
                      text: 提交作者：
                    - tag: a
                      text: ${{ github.event.pusher.username }}
                      href: ${{ github.server_url }}/${{ github.event.pusher.username }}
                  - - tag: text
                      text: 预览链接：
                    - tag: a
                      text: ${{ steps.vercel-deployment.outputs.preview-url }}
                      href: ${{ steps.vercel-deployment.outputs.preview-url }}
